import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen items-center bg-primary text-default`}>
        <div className='p-4 md:p-10 w-full max-w-[1256px]'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
